package com.friendly.commons.models.reports;

public enum ReportType {
    DEVICE_REGISTRATION,
    ACTIVE_SESSIONS,
    SESSION_STATISTIC,
    USER_ACTIVITY_DEVICE,
    USER_ACTIVITY_SYSTEM,
    STATISTIC_OPERATIONS,
    DEVICE_UPDATE,
    DEVICE_HISTORY,
    DEVICE_DISTRIBUTION,
    DEVICE_ONLINE,
    DEVICE_OFFLINE,
    DEVICE_EVENT,
    PROFILE_DOWNLOAD,
    FIRMWARE_VERSION,
    GROUP_UPDATE
}
